// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfI2D3QwE6ULN6Vq6aiMJIet9z4pHIaAY',
    appId: '1:442723121540:web:afaed35b4677c5d0aa05d1',
    messagingSenderId: '442723121540',
    projectId: 'sudan-it-marketplace',
    authDomain: 'sudan-it-marketplace.firebaseapp.com',
    storageBucket: 'sudan-it-marketplace.firebasestorage.app',
    measurementId: 'G-MNZ39J821F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABPe74RmgFdwR526Rnk8f8Us550ogDD0Q',
    appId: '1:442723121540:android:252596fce3cff33aaa05d1',
    messagingSenderId: '442723121540',
    projectId: 'sudan-it-marketplace',
    storageBucket: 'sudan-it-marketplace.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsLh1kXIQSorb8GBOsdJJeFTsoaEiWN34',
    appId: '1:442723121540:ios:69f6b1e661874ecfaa05d1',
    messagingSenderId: '442723121540',
    projectId: 'sudan-it-marketplace',
    storageBucket: 'sudan-it-marketplace.firebasestorage.app',
    iosBundleId: 'com.example.sudanItMarketplace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsLh1kXIQSorb8GBOsdJJeFTsoaEiWN34',
    appId: '1:442723121540:ios:69f6b1e661874ecfaa05d1',
    messagingSenderId: '442723121540',
    projectId: 'sudan-it-marketplace',
    storageBucket: 'sudan-it-marketplace.firebasestorage.app',
    iosBundleId: 'com.example.sudanItMarketplace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfI2D3QwE6ULN6Vq6aiMJIet9z4pHIaAY',
    appId: '1:442723121540:web:b5ef452c590b8737aa05d1',
    messagingSenderId: '442723121540',
    projectId: 'sudan-it-marketplace',
    authDomain: 'sudan-it-marketplace.firebaseapp.com',
    storageBucket: 'sudan-it-marketplace.firebasestorage.app',
    measurementId: 'G-B37NPWXS2E',
  );
}
